/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.32
 * Generated at: 2014-07-07 08:12:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.Info;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.SearchHelper;
import java.util.Map;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.Map.Entry;
import java.util.List;
import java.util.HashMap;
import java.util.ArrayList;
import org.opensolaris.opengrok.configuration.Project;
import org.opensolaris.opengrok.search.QueryBuilder;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.Prefix;
import org.opensolaris.opengrok.web.Util;
import java.util.EnumSet;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.Prefix;

public final class help_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


    private PageConfig cfg;


/* ---------------------- foot.jspf members start --------------------- */
    private static EnumSet<Prefix> needAddDiv = EnumSet.of(
        Prefix.HIST_L, Prefix.XREF_P, Prefix.DIFF_P, Prefix.MORE_P,
        // could NOT find any mapping/reference to those ones:
        Prefix.HIST_S, Prefix.XREF_S, Prefix.DIFF_S, Prefix.MORE_S);
/* ---------------------- foot.jspf members end --------------------- */

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/menu.jspf", Long.valueOf(1396943084000L));
    _jspx_dependants.put("/pageheader.jspf", Long.valueOf(1396943084000L));
    _jspx_dependants.put("/foot.jspf", Long.valueOf(1396943084000L));
    _jspx_dependants.put("/pageconfig.jspf", Long.valueOf(1396943084000L));
    _jspx_dependants.put("/httpheader.jspf", Long.valueOf(1396943084000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;


/* ---------------------- help.jsp start --------------------- */
{
    cfg = PageConfig.get(request);
    cfg.setTitle("OpenGrok Help");


/* ---------------------- httpheader.jsp start --------------------- */
{
    cfg = PageConfig.get(request);
    String styleDir = cfg.getCssDir();
    String ctxPath = request.getContextPath();
    String dstyle = styleDir + '/' + "style.css";
    String pstyle = styleDir + '/' + "print.css";

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n");
      out.write("    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<meta name=\"generator\" content=\"{OpenGrok ");
      out.print(Info.getVersion());
      out.write(' ');
      out.write('(');
      out.print(Info.getRevision());
      out.write(")\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=8\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(styleDir);
      out.write("/img/icon.png\" type=\"image/png\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Default\" href=\"");
      out.print( dstyle );
      out.write("\" />\n");
      out.write("<link rel=\"alternate stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Paper White\" href=\"");
      out.print( pstyle );
      out.write("\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/print.css\" media=\"print\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery.tooltip.css\" />\n");
      out.write("\n");
      out.write("<link rel=\"search\" href=\"");
      out.print(ctxPath);
      out.write("/opensearch\"\n");
      out.write("    type=\"application/opensearchdescription+xml\"\n");
      out.write("    title=\"OpenGrok Search for current project(s)\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/jquery-1.4.4.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/jquery.tooltip-1.3.pack.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/utils.js\"></script>\n");
      out.write("<title>");
      out.print(cfg.getTitle());
      out.write("</title>");

    out.write(cfg.getHeaderData());

      out.write("\n");
      out.write("</head>");

}
/* ---------------------- httpheader.jsp end --------------------- */

      out.write("\n");
      out.write("<body>\n");
      out.write("    <div id=\"page\">\n");
      out.write("        <div id=\"whole_header\">\n");
      out.write("            <div id=\"header\">");
 
/* ---------------------- pageheader.jspf start --------------------- */
{
    cfg = PageConfig.get(request);

      out.write("\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/\"><span id=\"MastheadLogo\"></span></a>\n");
      out.print( cfg.getEnv().getConfiguration().getHeaderIncludeFileContent() );
      out.write('\n');
 
}
/* ---------------------- pageheader.jspf end --------------------- */

      out.write('\n');
      out.write("</div>\n");
      out.write("            <div id=\"Masthead\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"sbar\">\n");
      out.write("            <div id=\"menu\">");
      out.write('\n');
      out.write('\n');

/* ---------------------- menu.jspf start --------------------- */
{
    // PageConfig cfg = PageConfig.get(request);

    List<Project> projects = cfg.getEnv().getProjects();
    if (projects == null) {
        projects = new ArrayList<Project>(0);
    }
    TreeMap<String, String> pMap = new TreeMap<String, String>();
    QueryBuilder queryParams = cfg.getQueryBuilder();
    if (projects.size() != 0) {
        for (Project p : projects) {
            String name = p.getDescription();
            String esc = Util.formQuoteEscape(p.getDescription());
            pMap.put(name, esc);
        }
        StringBuilder jsProjects = new StringBuilder(64);
        jsProjects.append('\'');
        for (String name : cfg.getRequestedProjects()) {
            jsProjects.append(name).append("','");
        }
        if (jsProjects.length() > 1) {
            jsProjects.setLength(jsProjects.length()-2);
        } else {
            jsProjects.setLength(0);
        }

      out.write("\n");
      out.write("<script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("    document.projects = [ ");
      out.print( Util.encode(jsProjects.toString())
    );
      out.write(" ];document.xrefPath = '");
      out.print( request.getContextPath() + Prefix.XREF_P
    );
      out.write("';document.domReady.push(function() { domReadyMenu(); });\n");
      out.write("/* ]]> */\n");
      out.write("</script>");

    }

      out.write("\n");
      out.write("<form action=\"search\" id=\"sbox\">\n");
      out.write("\n");
      out.write("<div id=\"qtbl\">\n");
      out.write("<table>\n");
      out.write("    <tr>\n");
      out.write("        <td><label for=\"s1\" title=\"The text token(s) or other fields to be found (lucene query, this is not full text!)\">Full&nbsp;Search</label></td>\n");
      out.write("        <td><input tabindex=\"1\" class=\"q\" name=\"q\" id=\"q\" value=\"");
      out.print(
                Util.formQuoteEscape(queryParams.getFreetext()) );
      out.write("\"/></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("\t    <td><label for=\"s2\" title=\"Definition of function/variable/class\">Definition</label></td>\n");
      out.write("        <td><input class=\"q\" tabindex=\"2\" name=\"defs\" id=\"defs\" value=\"");
      out.print(
            Util.formQuoteEscape(queryParams.getDefs()) );
      out.write("\"/></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td><label for=\"s3\" title=\"Usage of function/variable/class\">Symbol</label></td>\n");
      out.write("        <td><input class=\"q\" tabindex=\"3\" name=\"refs\" id=\"refs\" value=\"");
      out.print(
            Util.formQuoteEscape(queryParams.getRefs()) );
      out.write("\"/></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td><label for=\"s4\" title=\"path or parts of it, no need to use dividers\">File&nbsp;Path</label></td>\n");
      out.write("        <td><input class=\"q\" tabindex=\"4\" name=\"path\" id=\"path\" value=\"");
      out.print(
            Util.formQuoteEscape(queryParams.getPath()) );
      out.write("\"/></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td><label for=\"s5\" title=\"Search in log messages\">History</label></td>\n");
      out.write("        <td><input class=\"q\" tabindex=\"5\" name=\"hist\" id=\"hist\" value=\"");
      out.print(
            Util.formQuoteEscape(queryParams.getHist()) );
      out.write("\"/></td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("        <td><label for=\"s5\">Type</label></td>\n");
      out.write("        <td><select class=\"q\" tabindex=\"6\" name=\"type\" id=\"type\">");

                String selection = queryParams.getType();  
                
      out.write("\n");
      out.write("                <option value=\"\">Any</option>");

                for (Map.Entry<String, String> d : SearchHelper.getFileTypeDescirptions()) {
                    
      out.write("\n");
      out.write("                <option value=\"");
      out.print( Util.formQuoteEscape(d.getKey()) );
      out.write('"');

                    if (d.getKey().equals(selection)) {
                        
      out.write(" selected=\"selected\"");

                    }
                    
      out.write('>');
      out.print( Util.htmlize(d.getValue()) );
      out.write("</option>");

                }
            
      out.write("\n");
      out.write("            </select>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("</div>");


    if (projects.size() != 0) {

      out.write("\n");
      out.write("<div id=\"ptbl\">\n");
      out.write("    <p><label for=\"project\">In Project(s)</label> <button tabindex=\"6\" type=\"button\"\n");
      out.write("        onclick=\"javascript: selectAllProjects(); return false;\"\n");
      out.write("        >select all</button>&nbsp;<button tabindex=\"7\" type=\"button\"\n");
      out.write("        onclick=\"javascript: invertAllProjects(); return false;\"\n");
      out.write("        >invert selection</button> </p>\n");
      out.write("    <select tabindex=\"8\" ondblclick=\"javascript: goFirstProject();\"\n");
      out.write("        onkeyup=\"javascript: checkEnter(event);\" class=\"q\" id=\"project\"\n");
      out.write("        name=\"project\" multiple=\"multiple\" size=\"");
      out.print(
        Math.min(6, projects.size()) );
      out.write('"');
      out.write('>');

        SortedSet<String> pRequested = cfg.getRequestedProjects();
        for (Entry<String,String> e : pMap.entrySet()) {
            // TODO below "selected" has no effect if one refreshes the page
            // with F5 also below ondblclick doesn't work in IE ...
            // ondblclick="javascript:goFirstProject();"
        
      out.write("\n");
      out.write("        <option value=\"");
      out.print( e.getValue() );
      out.write('"');

            if (pRequested.contains(e.getKey())) {
            
      out.write(" selected=\"selected\"");

            }
            
      out.write('>');
      out.print( e.getValue() );
      out.write("</option>");

        }
        
      out.write("\n");
      out.write("    </select>\n");
      out.write("</div>");

    }
    
      out.write("\n");
      out.write("\n");
      out.write("    <p><input tabindex=\"9\" class=\"submit\" type=\"submit\" value=\"Search\"/> \n");
      out.write("    <input tabindex=\"10\" class=\"submit\" onclick=\"javascript: clearSearchFrom();\" \n");
      out.write("\t   type=\"button\" value=\" Clear \"/> \n");
      out.write("    <button class=\"help\" tabindex=\"11\" onclick=\"window.open('help.jsp');\">Help\n");
      out.write("    </button>\n");
      out.write("    </p>\n");
      out.write("</form>\n");

}
/* ---------------------- menu.jspf end --------------------- */

      out.write('\n');
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"help\">\n");
      out.write("<p>\n");
      out.write("\n");
      out.write("<dfn><b>Examples:</b></dfn>\n");
      out.write("<pre class=\"example\">\n");
      out.write("\n");
      out.write("To find where setResourceMonitors is defined: \n");
      out.write("<a href=\"search?q=&amp;defs=setResourceMonitors\">defs:setResourceMonitors</a>\n");
      out.write("\n");
      out.write("To find files that use sprintf in usr/src/cmd/cmd-inet/usr.sbin/:\n");
      out.write("<a href=\"search?refs=sprintf&amp;path=usr%2Fsrc%2Fcmd%2Fcmd-inet%2Fusr.sbin%2F\"\n");
      out.write(">refs:sprintf path:usr/src/cmd/cmd-inet/usr.sbin</a>\n");
      out.write("\n");
      out.write("To find assignments to variable foo:\n");
      out.write("<a href=\"search?q=%22foo+%3D%22\">\"foo =\"</a>\n");
      out.write("\n");
      out.write("To find Makefiles where pstack binary is being built:\n");
      out.write("<a href=\"search?q=pstack&amp;path=Makefile\">pstack path:Makefile</a>\n");
      out.write("\n");
      out.write("to search for phrase \"Bill Joy\":\n");
      out.write("<a href=\"search?q=%22Bill+Joy%22\">\"Bill Joy\"</a>\n");
      out.write("\n");
      out.write("To find perl files that do not use /usr/bin/perl but something else:\n");
      out.write("<a href=\"search?q=-%22%2Fusr%2Fbin%2Fperl%22+%2B%22%2Fbin%2Fperl%22\"\n");
      out.write(">-\"/usr/bin/perl\" +\"/bin/perl\"</a>\n");
      out.write("\n");
      out.write("To find all strings beginning with foo use the wildcard:\n");
      out.write("<a href=\"search?q=foo*\">foo*</a>\n");
      out.write("\n");
      out.write("To find all files which have . c in their name (dot is a token!):\n");
      out.write("<a href=\"search?path=%22. c%22\">\". c\"</a>\n");
      out.write("\n");
      out.write("To find all files which start with \"ma\" and then have only alphabet characters do:\n");
      out.write("<a href=\"search?path=/ma[a-zA-Z]*/\">path:/ma[a-zA-Z]*/</a>\n");
      out.write("\n");
      out.write("To find all main methods in all files analyzed by C analyzer (so .c, .h, ...) do:\n");
      out.write("<a href=\"search?q=main&type=c\">main type:c</a>\n");
      out.write("</pre>\n");
      out.write("<br/>\n");
      out.write("<dfn><b>More info:</b></dfn><br/><br/>\n");
      out.write("A <dfn>Query</dfn> is a series of clauses. A clause may be prefixed by:</p>\n");
      out.write("<ul>\n");
      out.write("    <li>a plus \"<b>+</b>\" or a minus \"<b>-</b>\" sign, indicating that the clause\n");
      out.write("        is required or prohibited respectively; or</li>\n");
      out.write("    <li>a <dfn>term</dfn> followed by a colon \"<b>:</b>\", indicating the\n");
      out.write("        <dfn>field</dfn> to be searched. This enables one to construct queries\n");
      out.write("        which search multiple <dfn>fields</dfn>.</li>\n");
      out.write("</ul>\n");
      out.write("<p>A clause may be either:</p>\n");
      out.write("<ul>\n");
      out.write("    <li>a <dfn>term</dfn>, indicating all the documents that contain this term;\n");
      out.write("        or</li>\n");
      out.write("    <li>a <dfn>phrase</dfn> - group of words surrounded by double quotes\n");
      out.write("        <b>\" \"</b>, e.g. \"hello dolly\"  </li>\n");
      out.write("    <li>a nested query, enclosed in parentheses \"<b>(</b>\" \"<b>)</b>\" (also\n");
      out.write("        called query/field <dfn>grouping</dfn>) . Note that this may be used\n");
      out.write("        with a +/- prefix to require any of a set of terms. </li>\n");
      out.write("    <li>boolean <dfn>operators</dfn> which allow terms to be combined through\n");
      out.write("        logic operators. Supported are <b>AND</b>(<b>&amp;&amp;</b>), \"<b>+</b>\",\n");
      out.write("        <b>OR</b>(<b>||</b>), <b>NOT</b>(<b>!</b>) and \"<b>-</b>\" (Note: they\n");
      out.write("        must be ALL CAPS).</li>\n");
      out.write("</ul>\n");
      out.write("<p>Regular Expression, Wildcard, Fuzzy, Proximity &amp; Range Searches:</p>\n");
      out.write("<ul>\n");
      out.write("    <li>to perform a regular expression search use the \"<b>/</b>\" enclosure,\n");
      out.write("        e.g.  /[mb]an/ - will search for man or for ban;<br>\n");
      out.write("        NOTE: path field search escapes \"/\" by default, so it only supports \n");
      out.write("        regexps when the search string <u>starts and ends</u> with \"/\".<br>\n");
      out.write("        More info can be found on <a href=\"http://lucene.apache.org/core/4_5_1/core/org/apache/lucene/util/automaton/RegExp.html?is-external=true\">lucene regexp page</a>.\n");
      out.write("    </li>\n");
      out.write("    <li>to perform a single character wildcard search use the \"<b>?</b>\" symbol,\n");
      out.write("        e.g.  te?t</li>\n");
      out.write("    <li>to perform a multiple character wildcard search use the \"<b>*</b>\"\n");
      out.write("        symbol, e.g. test* or te*t</li>\n");
      out.write("    <li>you can use a * or ? symbol as the first character of a search\n");
      out.write("        (unless not enabled using indexer option -a).</li>\n");
      out.write("    <li>to do a fuzzy search (find words similar in spelling, based on the\n");
      out.write("        Levenshtein Distance, or Edit Distance algorithm) use the tilde,\n");
      out.write("        \"<b>~</b>\", e.g. rcs~ </li>\n");
      out.write("    <li>to do a proximity search use the tilde, \"~\", symbol at the end of a\n");
      out.write("        Phrase. For example to search for a \"opengrok\" and \"help\" within 10\n");
      out.write("        words of each other enter: \"opengrok help\"~10 </li>\n");
      out.write("    <li>range queries allow one to match documents whose field(s) values are\n");
      out.write("        between the lower and upper bound specified by the Range Query. Range\n");
      out.write("        Queries can be inclusive or exclusive of the upper and lower bounds.\n");
      out.write("        Sorting is done lexicographically. Inclusive queries are denoted by\n");
      out.write("        square brackets <b>[ ]</b> , exclusive by curly brackets <b>{ }</b>.\n");
      out.write("        For example: title:{Aida TO Carmen} - will find all documents between\n");
      out.write("        Aida to Carmen, exclusive of Aida and Carmen. </li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("<a id=\"escaping\"><dfn>Escaping special characters:</dfn></a>\n");
      out.write("<p>Opengrok supports escaping special characters that are part of the query\n");
      out.write("    syntax. Current special characters are:<br/>\n");
      out.write("    <b>+ - &amp;&amp; || ! ( ) { } [ ] ^ \" ~ * ? : \\ / </b><br/>\n");
      out.write("To escape these character use the \\ before the character. For example to search\n");
      out.write("for <b>(1+1):2</b> use the query: <b>\\(1\\+1\\)\\:2</b>\n");
      out.write("</p>\n");
      out.write("<p>NOTE on analyzers: Indexed words are made up of Alpha-Numeric and Underscore\n");
      out.write("characters. One letter words are usually not indexed as symbols!<br/>\n");
      out.write("Most other characters (including single and double quotes) are treated as\n");
      out.write("\"spaces/whitespace\" (so even if you escape them, they will not be found, since\n");
      out.write("most analyzers ignore them). <br/>\n");
      out.write("The exceptions are: <b>@ $ % ^ &amp; = ? . :</b> which are mostly indexed as\n");
      out.write("separate words.<br/>\n");
      out.write("Because some of them are part of the query syntax, they must be escaped with a\n");
      out.write("reverse slash as noted above.<br/>\n");
      out.write("So searching for <b>\\+1</b> or <b>\\+ 1</b> will both find <b>+1</b> and <b>+ 1</b>.\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<p>valid <dfn>FIELDs</dfn> are</p>\n");
      out.write("    <dl class=\"fields\">\n");
      out.write("<dt>full</dt>\n");
      out.write("<dd>Search through all text tokens (words,strings,identifiers,numbers) in index.</dd>\n");
      out.write("\n");
      out.write("<dt>defs</dt>\n");
      out.write("<dd>Only finds symbol definitions (where e.g. a variable (function, ...) is defined).</dd>\n");
      out.write("\n");
      out.write("<dt>refs</dt>\n");
      out.write("<dd>Only finds symbols (e.g. methods, classes, functions, variables).</dd>\n");
      out.write("\n");
      out.write("<dt>path</dt>\n");
      out.write("<dd>path of the source file (no need to use dividers, or if, then use \"/\" - Windows users, \"\\\" is an escape key in lucene query syntax! <br/>Please don't use \"\\\", or replace it with \"/\").<br/>Also note that if you want just exact path, enclose it in \"\", e.g. \"src/mypath\", otherwise dividers will be removed and you get more hits.</dd>\n");
      out.write("\n");
      out.write("<dt>hist</dt>\n");
      out.write("<dd>History log comments.</dd>\n");
      out.write("\n");
      out.write("<dt>type</dt>\n");
      out.write("<dd>Type of analyzer used to scope down to certain file types (e.g. just C sources).<br/>Current mappings: ");
      out.print(SearchHelper.getFileTypeDescirptions().toString());
      out.write("</dd>\n");
      out.write("\n");
      out.write("    </dl>\n");
      out.write("\n");
      out.write("<p>\n");
      out.write("the term (phrases) can be boosted (making it more relevant) using a caret\n");
      out.write("<b>^</b> , e.g. help^4 opengrok - will make term help boosted\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<p>Opengrok search is powered by <a href=\"http://lucene.apache.org/\"\n");
      out.write(">lucene</a>, for more detail on query syntax refer to <a href=\"http://lucene.apache.org/core/4_7_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description\">lucene docs</a>.<br>\n");
      out.write("</p>\n");
      out.write("        </div>\n");

}
/* ---------------------- help.jsp end --------------------- */


/* ---------------------- foot.jspf start --------------------- */
{
    cfg = PageConfig.get(request);

        
      out.write("\n");
      out.write("    <div id=\"footer\">\n");
      out.write("<p><a href=\"http://opengrok.github.com/OpenGrok/\"\n");
      out.write(" title=\"Served by OpenGrok\"><span id=\"fti\"></span></a></p>\n");
      out.write("<p>Indexes created ");
      out.print( cfg.getEnv().getDateForLastIndexRun() );
      out.write("</p>\n");
      out.write("    ");
      out.print( cfg.getEnv().getConfiguration().getFooterIncludeFileContent() );
      out.write("\n");
      out.write("    ");

    if (needAddDiv.contains(cfg.getPrefix())) {
        
      out.write("</div>");
 // #content
    }
    // #footer, #page:
    
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

}
/* ---------------------- foot.jspf end --------------------- */

      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
